---

- name: Déploiement sur les serveurs web
  hosts: web
  roles:
    - common
    - nfs
  tasks:
    - name: Tâches web Apache
      include_tasks: tasks/web-apache.yml
    - name: Tâches web WP
      include_tasks: tasks/web-wp.yml
  handlers:
  # sudo systemctl restart nfs-kernel-server
  - name: Redémarrer nfs-kernel-server
    service: 
      name: nfs-kernel-server
      state: restarted
  # sudo systemctl restart apache2
  - name: Redémarrer Apache
    service: 
      name: apache2
      state: restarted

- name: Déploiement sur les serveurs PHP
  hosts: php
  roles:
    - common
    - php-fpm
    - nfs

- name: Déploiement sur les serveurs DB
  hosts: db
  roles:
    - common
    - lukasic.mariadb