---

- name: Déploiement sur l'infra
  hosts: all
  tasks:
    - name: Tâches all-nodes
      include_tasks: tasks/all-nodes.yml

- name: Déploiement sur les serveurs web
  hosts: web
  tasks:
    - name: Tâches web Apache
      include_tasks: tasks/web-apache.yml
    - name: Tâches web WP
      include_tasks: tasks/web-wp.yml
    - name: Tâches web NFS
      include_tasks: tasks/web-nfs.yml
  handlers:
  # sudo systemctl restart nfs-kernel-server
  - name: Redémarrer nfs-kernel-server
    service: 
      name: nfs-kernel-server
      state: restarted
  # sudo systemctl restart apache2
  - name: Redémarrer Apache
    service: 
      name: apache2
      state: restarted

- name: Déploiement sur les serveurs PHP
  hosts: php
  tasks:
    - name: Tâches PHP-FPM
      include_tasks: tasks/php-fpm.yml
    - name: Tâches PHP NFS
      include_tasks: tasks/php-nfs.yml
  handlers:
  - name: Redémarrer PHP-FPM
    service: 
      name: "php{{ php_version.stdout }}-fpm"
      state: restarted