---

- name: Déploiement sur les serveurs web
  hosts: web
  roles:
    - common
    - nfs
    - apache
  tasks:
    - name: Tâches web WP
      include_tasks: tasks/web-wp.yml

- name: Déploiement sur les serveurs PHP
  hosts: php
  roles:
    - common
    - php-fpm
    - nfs

- name: Déploiement sur les serveurs DB
  hosts: db
  roles:
    - common
    - lukasic.mariadb