---

# sudo apt install apache2 git
- name: Installer les paquets nécessaires
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - apache2
    - git

# Autre forme qui occupe moins de lignes
#- name: Installer Apache
#  apt: name=apache2 state=latest

#wget https://wordpress.org/latest.zip -O /tmp/wordpress.zip
# - name: Télécharger wordpress
#   get_url:
#     url: https://wordpress.org/latest.zip
#     dest: /tmp/wordpress.zip

#sudo apt install unzip
# - name: Installer unzip
#   apt:
#     name: unzip
#     state: latest

#unzip latest.zip
# - name: Dézipper wordpress
#   unarchive:
#     src: /tmp/wordpress.zip
#     dest: /var/www/
#     remote_src: yes

# Configuration de git
- name: Configuration de Git
  copy:
    src: files/root-gitconfig
    dest: /root/.gitconfig

# Autre façon de faire : git checkout
- name: Synchroniser Wordpress depuis Github
  git:
    repo: "{{ wordpress_repo }}"
    dest: "{{ wordpress_path }}"
    version: "{{ wordpress_version }}"
    force: true

#sudo chown -R www-data:www-data /var/www/wordpress
- name: Changer le propriétaire des fichiers de wordpress
  file:
    path: "{{ wordpress_path }}"
    owner: "{{ wordpress_owner }}"
    group: "{{ wordpress_group }}"
    recurse: true

# Désactivation du virtualhost 000-default de Apache
- name: Désactivation de 000-default
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

# Création du vhost wordpress
- name: Configuration du vhost wordpress
  template:
    src: files/vhost-wordpress
    dest: /etc/apache2/sites-available/wordpress.conf

# Activation du vhost wordpress
- name: Activation du vhost wordpress
  file:
    src: /etc/apache2/sites-available/wordpress.conf
    dest: /etc/apache2/sites-enabled/wordpress.conf
    state: link

# sudo a2enmod proxy_fcgi
- name: Activation du module proxy_fcgi
  apache2_module:
    name: proxy_fcgi
    state: present

# sudo systemctl restart apache2
- name: Redémarrer Apache
  service: 
    name: apache2
    state: restarted